### ISSUE TITLE
See shared posts

### ISSUE THREAD

**Issue by tahlers93** [cedteg/flutter_fb_news#19]
Actual, a shared post is not directly evident. I see only the post of my site and the picture of the shared post. You should be able to see the text of the shared post and the name of the page.

**Comment by cedteg** [comment]
I agree with you there. I'll see what I can do there.

If you have an implementation possibility, I'm happy about Pr's

**Comment by cedteg** [comment]
it´s testable with [1.1.4-dev.2](https://pub.dev/packages/flutter_fb_news/versions/1.1.4-dev.2)
