### ISSUE TITLE
Set Background-Color for the posts

### ISSUE THREAD

**Issue by tahlers93** [cedteg/flutter_fb_news#5]
It would be nice to set an individuell background color for the posts.

**Comment by cedteg** [comment]
I will call it borderColor.

But in addition I add backgroundColor for the actual postbackgroundcolor and textColor for the textcolor

Then a post could look like this
![image](https://user-images.githubusercontent.com/40794239/105909862-638bd980-6028-11eb-958b-4164f0cf7139.png)

**Comment by cedteg** [comment]
can be tested with 1.1.0-dev.2

**Comment by tahlers93** [comment]
Thanks, but i have still a problem:

![image](https://user-images.githubusercontent.com/59026355/105954699-5c3eed00-6075-11eb-800f-26c16b5c58e7.png)

I try to set the bordercolor to transparent. 

Is the grey border a problem of my config or can you changed it? I dont want a border.

Thanks!

**Comment by cedteg** [comment]
I have added it as a new ticket #9 


can be tested with [1.1.0-dev.4](https://pub.dev/packages/flutter_fb_news/versions/1.1.0-dev.4/changelog)
